### ISSUE TITLE
OfficeBackend emits error when converting uploaded file

### ISSUE THREAD

**Issue by btimby** [btimby/preview-server#8]
The following error occurs because an upload is in `/tmp` which is not accessible to OO. In this case, we need to pass a file-like object and use `private:stream` / stdin to do the conversion.

```
preview-server_1  | Office probably died. Unsupported URL <file:///tmp/tmpduzfg5y2.pptx>: "type detection failed"
preview-server_1  | OfficeBackend.preview('/mnt/files/agreement.docx', 100, 124) took 9.370164s
nginx_1           | nginx.1    | preview 172.27.0.1 - - [01/Oct/2019:06:44:13 +0000] "GET /preview/?path=candea.pptx&width=103&height=310 HTTP/1.1" 200 2308 "-" "Python/3.6 aiohttp/4.0.0a0"
nginx_1           | nginx.1    | preview 172.27.0.1 - - [01/Oct/2019:06:44:13 +0000] "GET /preview/?path=agreement.docx&width=100&height=124 HTTP/1.1" 200 3738 "-" "Python/3.6 aiohttp/4.0.0a0"
preview-server_1  | improper image header `/tmp/tmpkbqabg2h.png' @ error/png.c/ReadPNGImage/3954
preview-server_1  | Traceback (most recent call last):
preview-server_1  |   File "/app/preview/__main__.py", line 160, in preview
preview-server_1  |     status, path = 200, await generate(path, format, width, height)
preview-server_1  |   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
preview-server_1  |     result = self.fn(*self.args, **self.kwargs)
preview-server_1  |   File "/app/preview/preview.py", line 43, in generate
preview-server_1  |     store_path = Backend.preview(path, width, height)
preview-server_1  |   File "/app/preview/preview.py", line 34, in preview
preview-server_1  |     return obj.preview(path, width, height)
preview-server_1  |   File "/app/preview/utils.py", line 53, in inner
preview-server_1  |     return f(*args, **kwargs)
preview-server_1  |   File "/app/preview/backends/office.py", line 155, in preview
preview-server_1  |     return PdfBackend().preview(t.name, width, height)
preview-server_1  |   File "/app/preview/utils.py", line 53, in inner
preview-server_1  |     return f(*args, **kwargs)
preview-server_1  |   File "/app/preview/backends/pdf.py", line 43, in preview
preview-server_1  |     return ImageBackend().preview(t.name, width, height)
preview-server_1  |   File "/app/preview/utils.py", line 53, in inner
preview-server_1  |     return f(*args, **kwargs)
preview-server_1  |   File "/app/preview/backends/image.py", line 43, in preview
preview-server_1  |     return resize_image(path, width, height)
preview-server_1  |   File "/app/preview/backends/image.py", line 17, in resize_image
preview-server_1  |     with Image(filename=path, resolution=300) as s:
preview-server_1  |   File "/usr/local/lib/python3.6/dist-packages/wand/image.py", line 8212, in __init__
preview-server_1  |     units=units)
preview-server_1  |   File "/usr/local/lib/python3.6/dist-packages/wand/image.py", line 8686, in read
preview-server_1  |     self.raise_exception()
preview-server_1  |   File "/usr/local/lib/python3.6/dist-packages/wand/resource.py", line 240, in raise_exception
preview-server_1  |     raise e
preview-server_1  | wand.exceptions.CorruptImageError: improper image header `/tmp/tmpkbqabg2h.png' @ error/png.c/ReadPNGImage/3954
preview-server_1  | OfficeBackend.preview('/mnt/files/sample.docx', 677, 242) took 12.502673s
```

**Comment by btimby** [comment]
Unoconv handles this by setting the flag `--stdin` and passing the file body in place of the path.

https://github.com/unoconv/unoconv/blob/master/unoconv#L996
https://github.com/unoconv/unoconv/blob/master/unoconv#L1340

**Comment by btimby** [comment]
Done.

**Comment by btimby** [comment]
I implemented stdin support for files outside the shared FS. However, libreoffice seems highly unstable when using this option. Leaving this open for now as it is unusable.

**Comment by btimby** [comment]
Instability was something else. This works.
